import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Skills Competition",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/admin">) {
  return (
      <div>

      </div>
  );
}
